- pipeline: "Pipeline"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/main"
  fail_on_prepare_env_warning: true
  resources: "XLARGE"
  actions:
  - action: "msbuild"
    type: "NATIVE_BUILD_WINDOWS"
    commands:
    - "nuget restore"
    - "msbuild"
    - "vukan-markovic/Github-Android-Action@1.2"
    distribution: "WINDOWS_SERVER_2019"
    instance_type: "COMPUTE_XLARGE"
