- pipeline: "Pipeline"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/main"
  fail_on_prepare_env_warning: true
  resources: "XLARGE"
  actions:
  - action: "msbuild"
    type: "NATIVE_BUILD_WINDOWS"
    commands:
    - "nuget restore"
    - "msbuild"
    instance_type: "COMPUTE_XLARGE"
